'use strict';
const input = document.getElementById('Enword');
const startButton = document.getElementById("start");
const words = [
  "abandon",
  "ability",
  "absence",
  "absolute",
  "academic",
  "accept",
  "accident",
  "accompany",
  "according",
  "account",
  "achieve",
  "acknowledge",
  "acquire",
  "adapt",
  "adequate",
  "adjust",
  "administration",
  "admit",
  "advance",
  "advantage",
  "advice",
  "affect",
  "afford",
  "agency",
  "agreement",
  "allow",
  "alternative",
  "analyze",
  "announce",
  "anxiety",
  "apparent",
  "apply",
  "approach",
  "appropriate",
  "approve",
  "argue",
  "arrange",
  "aspect",
  "assist",
  "assume",
  "attempt",
  "attitude",
  "attract",
  "available",
  "aware",
  "benefit",
  "brief",
  "capable",
  "category",
  "challenge",
  "character",
  "circumstance",
  "comment",
  "commit",
  "compare",
  "complete",
  "concern",
  "conclude",
  "conduct",
  "confirm",
  "consider",
  "construct",
  "consume",
  "contact",
  "contain",
  "contribute",
  "consequence",
  "construct",
  "consume",
  "convenient",
  "create",
  "culture",
  "decline",
  "define",
  "demonstrate",
  "deny",
  "depend",
  "describe",
  "design",
  "despite",
  "detail",
  "determine",
  "develop",
  "difference",
  "difficult",
  "discuss",
  "disease",
  "display",
  "effect",
  "effort",
  "emphasize",
  "enable",
  "encourage",
  "environment",
  "establish",
  "evaluate",
  "event",
  "evidence",
  "example",
  "excellent",
  "exist",
  "expand",
  "experience",
  "explain",
  "express",
  "factor",
  "feature",
  "function",
  "generation",
  "impact",
  "improve",
  "increase",
  "influence",
  "indicate",
  "individual",
  "industry",
  "information",
  "indicate",
  "interest",
  "introduce",
  "issue",
  "knowledge",
  "language",
  "lecture",
  "maintain",
  "major",
  "method",
  "necessary",
  "negative",
  "normal",
  "obtain",
  "opportunity",
  "participate",
  "performance",
  "positive",
  "predict",
  "prepare",
  "prevent",
  "process",
  "produce",
  "product",
  "protect",
  "provide",
  "purpose",
  "quality",
  "react",
  "recognize",
  "reduce",
  "refer",
  "require",
  "research",
  "resource",
  "respond",
  "result",
  "select",
  "significant",
  "solution",
  "specific",
  "structure",
  "succeed",
  "suggest",
  "support",
  "system",
  "technology",
  "theory",
  "traditional",
  "transfer",
  "understand",
  "variety",
  "value",
  "version",
  "visual",
  "volunteer"
];
let currentWord        = "";
let isPlaying          = false
startButton.addEventListener("click", () => {
  startGame();
});

  function startGame() {
    isPlaying = true;
    nextWord ();
  }
  function nextWord() {
    currentWord = words[Math.floor(Math.random() * words.length)];
    document.getElementById("target").textContent = currentWord;
    input.value = "";
    input.focus();
  }
  
  input.addEventListener("keydown", (event) => {
if (!isPlaying) return;

if (event.key === "Enter") {
  if (input.value === currentWord) {
    nextWord();
  } else {
    alert("ミス！");
  }
}
  }
  )
